### ISSUE TITLE
Cobblemon

### ISSUE THREAD

**Issue by yourcraft0** [Benjamin-Norton/Neruina#105]
This is more of a cosmetic issue. 
The game doesn't crash nor Neurina or Cobblemon mod are incompatible but Neurina will "kill" the Pokemon I have summoned out especially on the first choosing of a partner and sometimes it will kill the Pokemon while in a battle with another Pokemon. The battle will still progress like the Pokemon is still there and Neurina does not kill the next Pokemon summoned/switched out. It does not remove/kill any Pokemon or mobs walking around however, only if I summon a Pokemon or is out for more than 5 seconds, sometimes. 
I don't have a screenshot but Neurina does inform of that it has removed the entity, namely the Pokemon I have out, on the chat log.

**Comment by Bawnorton** [comment]
Send the logs

**Comment by yourcraft0** [comment]
The first two are my Pokemon that I have summoned, so far no instance of it happening while in battle.
![image](https://github.com/user-attachments/assets/c626405e-97e4-4045-a263-4629e68219cf)
![image](https://github.com/user-attachments/assets/0a105478-a612-44e2-806c-f0d6c1babfd7)

**Comment by Bawnorton** [comment]
hit copy crash and paste that here

**Comment by yourcraft0** [comment]
I don't have a crash to report or copy. Though I am testing out other mods. This is the most "stable" I have of the game, at the moment.

**Comment by Bawnorton** [comment]
<img width="126" alt="Screenshot 2024-09-19 at 3 21 03 PM" src="https://github.com/user-attachments/assets/c20890e2-2469-4b81-9a09-57e78faff44b">
This button

**Comment by yourcraft0** [comment]
Oh...

java.lang.ClassCastException: class com.cobblemon.mod.common.entity.pokemon.ai.goals.PokemonFollowOwnerGoal cannot be cast to class com.goby56.wakes.duck.ProducesWake (com.cobblemon.mod.common.entity.pokemon.ai.goals.PokemonFollowOwnerGoal and com.goby56.wakes.duck.ProducesWake are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @667a738)
	at net.minecraft.class_1350.handler$lgl000$wakes$onTeleport(class_1350.java:1517)
	at net.minecraft.class_1350.method_23343(class_1350.java:143)
	at net.minecraft.class_1350.method_23345(class_1350.java:126)
	at net.minecraft.class_1350.method_6268(class_1350.java:113)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:771)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_1471.method_5773(class_1471.java:35)
	at com.cobblemon.mod.common.entity.pokemon.PokemonEntity.method_5773(PokemonEntity.java:313)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.mixinextras$bridge$accept$206(class_1937.java)
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at net.minecraft.class_1937.wrapOperation$hid000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:13048)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by yourcraft0** [comment]
The one with Eevee:

java.lang.ClassCastException: class com.cobblemon.mod.common.entity.pokemon.ai.goals.PokemonFollowOwnerGoal cannot be cast to class com.goby56.wakes.duck.ProducesWake (com.cobblemon.mod.common.entity.pokemon.ai.goals.PokemonFollowOwnerGoal and com.goby56.wakes.duck.ProducesWake are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @667a738)
	at net.minecraft.class_1350.handler$lgl000$wakes$onTeleport(class_1350.java:1517)
	at net.minecraft.class_1350.method_23343(class_1350.java:143)
	at net.minecraft.class_1350.method_23345(class_1350.java:126)
	at net.minecraft.class_1350.method_6268(class_1350.java:113)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:771)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_1471.method_5773(class_1471.java:35)
	at com.cobblemon.mod.common.entity.pokemon.PokemonEntity.method_5773(PokemonEntity.java:313)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.mixinextras$bridge$accept$206(class_1937.java)
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at net.minecraft.class_1937.wrapOperation$hid000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:13048)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Bawnorton** [comment]
Remove the `wakes` mod

**Comment by yourcraft0** [comment]
Alright. I see, thanks. I have 400+ more to test. I will let you know if any more happen.
