### ISSUE TITLE
Neruina Crash, after Pressing Neruina Report

### ISSUE THREAD

**Issue by suerion** [Benjamin-Norton/Neruina#113]
Hey, i had added Neruina on my side, and had unintentionally clicked on creating an new Report. it crash the server with this issue

```
[14:46:20] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/apache/http/HttpEntity
        at knot/com.bawnorton.neruina.report.AutoReportHandler.createReports(AutoReportHandler.java:65) ~[Neruina-2.1.2-fabric+1.21.jar:?]
        at knot/com.bawnorton.neruina.command.NeruinaCommandHandler.executeReport(NeruinaCommandHandler.java:264) ~[Neruina-2.1.2-fabric+1.21.jar:?]
        at knot/com.mojang.brigadier.context.ContextChain.mixinextras$bridge$run$9(ContextChain.java) ~[brigadier-1.3.10.jar:?]
        at knot/com.mojang.brigadier.context.ContextChain.wrapOperation$fec000$melius-commands$runConditionally(ContextChain.java:562) ~[brigadier-1.3.10.jar:?]
        at knot/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at knot/net.minecraft.class_8865.method_54416(class_8865.java:29) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_8865.execute(class_8865.java:13) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_8856.method_54405(class_8856.java:8) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_8847.method_54388(class_8847.java:8) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_8854.method_54390(class_8854.java:107) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2170.method_54313(class_2170.java:379) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2170.method_9249(class_2170.java:309) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3244.method_58590(class_3244.java:1319) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3244.method_44356(class_3244.java:1307) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpEntity
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 27 more
```

CrashReport: https://mclo.gs/ipQJvp3

On Windows Server 2019
With Fabric 1.21.1 on 0.16.9

**Comment by Bawnorton** [comment]
I'll look into this

**Comment by Bawnorton** [comment]
Should be fixed, close if so

**Comment by suerion** [comment]
Hey, would be test tomorow
