### ISSUE TITLE
Causes Instant Player Disconnect

### ISSUE THREAD

**Issue by CreativeCubeMC** [Benjamin-Norton/Neruina#119]
Version: 1.21.1
Loader: Neoforge
Neoforge Version: 21.1.79
Mod Version: 2.2.3

Logs Down below:
```
java.lang.NullPointerException: Cannot invoke "com.bawnorton.neruina.config.Config$LogLevel.ordinal()" because "com.bawnorton.neruina.config.Config.getInstance().logLevel" is null
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.players.PlayerList.handler$cbe000$neruina$sendSuspendedInfoOnJoin(PlayerList.java:3983) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:badpackets.mixins.json:MixinPlayerList from mod badpackets,pl:mixin:APP:maxhealthfix.neoforge.mixins.json:MixinPlayerList from mod maxhealthfix,pl:mixin:APP:balm.neoforge.mixins.json:PlayerListMixin from mod balm,pl:mixin:APP:resourcefulconfig.mixins.json:common.PlayerListAccessor from mod resourcefulconfig,pl:mixin:APP:servercore.common.mixins.json:features.dynamic.PlayerListMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:optimizations.players.PlayerListMixin from mod servercore,pl:mixin:APP:neruina.mixins.json:PlayerManagerMixin from mod neruina,pl:mixin:APP:creeperoverhaul-common.mixins.json:PlayerListMixin from mod creeperoverhaul,pl:mixin:APP:ftbessentials-common.mixins.json:PlayerListAccess from mod ftbessentials,pl:mixin:APP:quasar-common.mixins.json:PlayerListMixin from mod quasar,pl:mixin:APP:kubejs.mixins.json:PlayerListMixin from mod kubejs,pl:mixin:APP:securitycraft.mixins.json:camera.PlayerListMixin from mod securitycraft,pl:mixin:APP:ars_nouveau.mixins.json:camera.PlayerListMixin from mod ars_nouveau,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:271) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:badpackets.mixins.json:MixinPlayerList from mod badpackets,pl:mixin:APP:maxhealthfix.neoforge.mixins.json:MixinPlayerList from mod maxhealthfix,pl:mixin:APP:balm.neoforge.mixins.json:PlayerListMixin from mod balm,pl:mixin:APP:resourcefulconfig.mixins.json:common.PlayerListAccessor from mod resourcefulconfig,pl:mixin:APP:servercore.common.mixins.json:features.dynamic.PlayerListMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:optimizations.players.PlayerListMixin from mod servercore,pl:mixin:APP:neruina.mixins.json:PlayerManagerMixin from mod neruina,pl:mixin:APP:creeperoverhaul-common.mixins.json:PlayerListMixin from mod creeperoverhaul,pl:mixin:APP:ftbessentials-common.mixins.json:PlayerListAccess from mod ftbessentials,pl:mixin:APP:quasar-common.mixins.json:PlayerListMixin from mod quasar,pl:mixin:APP:kubejs.mixins.json:PlayerListMixin from mod kubejs,pl:mixin:APP:securitycraft.mixins.json:camera.PlayerListMixin from mod securitycraft,pl:mixin:APP:ars_nouveau.mixins.json:camera.PlayerListMixin from mod ars_nouveau,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:188) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:badpackets.mixins.json:MixinServerConfigurationPacketListenerImpl from mod badpackets,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:8) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,re:computing_frames,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:821) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:826) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
```

**Comment by Bawnorton** [comment]
Should be fixed in 2.2.4
