### ISSUE TITLE
(Forge 1.18.2) Incompatibility with "Observable"

### ISSUE THREAD

**Issue by su226** [Benjamin-Norton/Neruina#16]
**Describe the Bug**
Minecraft will crash on startup when both the 'Observable' and 'Neruina' mods are present. It seems like the same problem as #3 (Except it's Fabric, not Forge)

**Versions**
Minecraft 1.18.2
Forge 40.2.10
Neruina 1.2.4
[Observable](https://modrinth.com/mod/observable) 2.2.3
[Architectury](https://modrinth.com/mod/architectury-api) (Required by Observable) 4.11.93
[Kotlin for Forge](https://modrinth.com/mod/kotlin-for-forge) (Required by Observable) 3.12.0

**Log**
<details><pre>[02Oct2023 22:15:52.895] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, su226, --version, 1.18.2, --gameDir, /home/su226/.local/share/PrismLauncher/instances/1.18.2/.minecraft, --assetsDir, /home/su226/.local/share/PrismLauncher/assets, --assetIndex, 1.18, --uuid, feb7e269ab41485f9986dd63cb0b8d79, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.10, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width, 1280, --height, 720]
[02Oct2023 22:15:52.897] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.8 by Alibaba
[02Oct2023 22:15:52.938] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/su226/.local/share/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2348!/ Service=ModLauncher Env=CLIENT
[02Oct2023 22:15:53.060] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/su226/.local/share/PrismLauncher/libraries/net/minecraftforge/fmlcore/1.18.2-40.2.10/fmlcore-1.18.2-40.2.10.jar is missing mods.toml file
[02Oct2023 22:15:53.060] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/su226/.local/share/PrismLauncher/libraries/net/minecraftforge/javafmllanguage/1.18.2-40.2.10/javafmllanguage-1.18.2-40.2.10.jar is missing mods.toml file
[02Oct2023 22:15:53.061] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/su226/.local/share/PrismLauncher/libraries/net/minecraftforge/lowcodelanguage/1.18.2-40.2.10/lowcodelanguage-1.18.2-40.2.10.jar is missing mods.toml file
[02Oct2023 22:15:53.061] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/su226/.local/share/PrismLauncher/libraries/net/minecraftforge/mclanguage/1.18.2-40.2.10/mclanguage-1.18.2-40.2.10.jar is missing mods.toml file
[02Oct2023 22:15:53.132] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 7 dependencies adding them to mods collection
[02Oct2023 22:15:53.542] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[02Oct2023 22:15:53.548] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2, --gameDir, /home/su226/.local/share/PrismLauncher/instances/1.18.2/.minecraft, --assetsDir, /home/su226/.local/share/PrismLauncher/assets, --uuid, feb7e269ab41485f9986dd63cb0b8d79, --username, su226, --assetIndex, 1.18, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --width, 1280, --height, 720]
[02Oct2023 22:15:53.851] [pool-3-thread-1/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.0-rc.4).
[02Oct2023 22:15:53.973] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed neruina-common.mixins.json:WorldMixin -> net.minecraft.world.level.Level: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/level/Level::catchTickingEntities with priority 1000 cannot inject into net/minecraft/world/level/Level::m_46653_(Ljava/util/function/Consumer;Lnet/minecraft/world/entity/Entity;)V merged by observable.mixin.LevelMixin with priority 1000 [PREINJECT Applicator Phase -> neruina-common.mixins.json:WorldMixin -> Prepare Injections ->  -> wrapOperation$zzf000$catchTickingEntities(Ljava/util/function/Consumer;Ljava/lang/Object;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/level/Level::catchTickingEntities with priority 1000 cannot inject into net/minecraft/world/level/Level::m_46653_(Ljava/util/function/Consumer;Lnet/minecraft/world/entity/Entity;)V merged by observable.mixin.LevelMixin with priority 1000 [PREINJECT Applicator Phase -> neruina-common.mixins.json:WorldMixin -> Prepare Injections ->  -> wrapOperation$zzf000$catchTickingEntities(Ljava/util/function/Consumer;Ljava/lang/Object;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraftforge.registries.GameData.init(GameData.java:123) ~[forge-1.18.2-40.2.10-universal.jar%2363!/:?]
	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:108) ~[forge-1.18.2-40.2.10-universal.jar%2363!/:?]
	at net.minecraft.core.Registry.forge(Registry.java:407) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.core.Registry.forge(Registry.java:391) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:170) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:138) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]</pre></details>

**Comment by Bawnorton** [comment]
Fixed in 1.2.5
