### ISSUE TITLE
error spam

### ISSUE THREAD

**Issue by JJandPenguin** [Benjamin-Norton/Neruina#24]
it keeps spamming this error in ingame chat neruina.ticking.entity and its getting a little annoying (im using 1.19.2) is there a way you can turn this error notification off?

**Comment by Bawnorton** [comment]
Yes, fix the underlying error that is causing the messages. It'll be in your log.

**Comment by JJandPenguin** [comment]
the entity that is causing it just like doesn't exist here 

<details>
net.minecraft.ReportedException: Ticking entity
        at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:67) ~[ItShallNotTick-1.0.11-build.35.jar%23264!/:1.0.11-build.35] {re:mixin,re:classloading}
        at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:24) ~[ItShallNotTick-1.0.11-build.35.jar%23264!/:1.0.11-build.35] {re:mixin,re:classloading}
        at net.minecraft.world.level.Level.mixinextras$bridge$entityTicking$135(Level.java) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:neruina.mixins.json:itshallnottick.WorldMixin,pl:mixin:A}
        at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:119) ~[neruina-1.2.6-forge+1.18.2-1.20.1.jar%23279!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.Level.wrapOperation$zke000$catchTickingEntities(Level.java:2542) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:neruina.mixins.json:itshallnottick.WorldMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_46653_(Level.java:1539) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:neruina.mixins.json:itshallnottick.WorldMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:APP:neruina-common.mixins.json:ServerWorldMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:APP:immersive_melodies.mixin.json:ServerWorldMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
        at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:classloading}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:APP:neruina-common.mixins.json:ServerWorldMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:APP:immersive_melodies.mixin.json:ServerWorldMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.phys.AABB net.minecraft.world.entity.item.ItemEntity.m_142469_()'
        at net.minecraft.world.entity.item.ItemEntity.handler$zfg000$checkSize(ItemEntity.java:1056) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,re:classloading,pl:mixin:APP:itshallnottick.mixins.json:ItemEntityMixin,pl:mixin:APP:leaky.mixins.json:ItemEntityMixin,pl:mixin:APP:display_case.mixins.json:ItemEntityMixin,pl:mixin:APP:backpacked.mixins.json:common.ItemEntityMixin,pl:mixin:A}
        at net.minecraft.world.entity.item.ItemEntity.m_8119_(ItemEntity.java:174) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,re:classloading,pl:mixin:APP:itshallnottick.mixins.json:ItemEntityMixin,pl:mixin:APP:leaky.mixins.json:ItemEntityMixin,pl:mixin:APP:display_case.mixins.json:ItemEntityMixin,pl:mixin:APP:backpacked.mixins.json:common.ItemEntityMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:APP:neruina-common.mixins.json:ServerWorldMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:APP:immersive_melodies.mixin.json:ServerWorldMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
        at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:61) ~[ItShallNotTick-1.0.11-build.35.jar%23264!/:1.0.11-build.35] {re:mixin,re:classloading}
        ... 14 more
</details>

**Comment by Bawnorton** [comment]
Please upload the full log to https://mclo.gs and send the link here.

**Comment by JJandPenguin** [comment]
https://mclo.gs/gv7iDRv
thats there error when i removed the mod

**Comment by Bawnorton** [comment]
This log is for a server watch dog, I mean the log that contained [this](https://github.com/Bawnorton/Neruina/issues/24#issuecomment-1777519811) but, the rest of it. The log you copy pasted here has been truncated so I can't find the true cause.

**Comment by Bawnorton** [comment]
> thats there error when i removed the mod

.. Removing Neruina means your server will just crash, Neruina is stopping your server from crashing which is why it exists

**Comment by JJandPenguin** [comment]
https://mclo.gs/RZt1j7C

**Comment by Bawnorton** [comment]
Cause is not clear, check your mod versions, one of them is trying to check the size of an item but using code from a different version of mc, implying that one of your mods is not supposed to be used on 1.19.2.

**Comment by Bawnorton** [comment]
Do a binary search if you can't find it. Make a backup first of course.

> A binary search can be used to quickly find a specific mod causing trouble, which can be especially useful when logs don't give a conclusive answer to your issue.

> Start by removing or disabling half of your mods, then test if the problem still occurs. If it does, remove half of the remaining mods and test again. If it doesn't, add back half of the mods you just removed.

> Keep in mind you don't have to stick strictly to halves each time, and may have to enable some library mods like Fabric API out of order.

> By repeating this on an increasingly smaller set of mods, you'll find the problematic mod within a few iterations.

**Comment by JJandPenguin** [comment]
will try

**Comment by JJandPenguin** [comment]
thanks resolved
