### ISSUE TITLE
Create Deployer

### ISSUE THREAD

**Issue by kecsong** [Benjamin-Norton/Neruina#39]
Currently hosting a server, got this log, can you help me? 
[latest.log](https://github.com/Bawnorton/Neruina/files/13956719/latest.log)

[00:20:26] [Server thread/WARN]: Neruina Caught Exception
java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "capturedDrops" is null
	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activateInner(DeployerHandler.java:207) ~[Prominent-Create-0.5.1-d-maybefix+mc1.20.1.jar:?]
	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activate(DeployerHandler.java:134) ~[Prominent-Create-0.5.1-d-maybefix+mc1.20.1.jar:?]
	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.activate(DeployerBlockEntity.java:358) ~[Prominent-Create-0.5.1-d-maybefix+mc1.20.1.jar:?]
	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.tick(DeployerBlockEntity.java:244) ~[Prominent-Create-0.5.1-d-maybefix+mc1.20.1.jar:?]
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15) ~[Prominent-Create-0.5.1-d-maybefix+mc1.20.1.jar:?]
	at net.minecraft.class_2818$class_5563.mixinextras$bridge$tick$11(class_2818.java) ~[server-intermediary.jar:?]
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickBlockEntity$notTheCauseOfTickLag(NeruinaTickHandler.java:96) ~[neruina-1.3.0-fabric+1.18.2-1.20.1.jar:?]
	at net.minecraft.class_2818$class_5563.wrapOperation$dlg000$neruina$catchTickingBlockEntity(class_2818.java:1285) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:470) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:390) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Bawnorton** [comment]
https://github.com/Fabricators-of-Create/Create/issues/1096

**Comment by kecsong** [comment]
thanks
