### ISSUE TITLE
[1.20.1] Corail Tombstone ticking entity crash with Neruina (Random ticking entity crash. Perhaps related to a Receptable with a Familar?)

### ISSUE THREAD

**Issue by Gbergz** [Benjamin-Norton/Neruina#65]
### Minecraft Version

1.20.1

### Forge Version

47.2.17

### Neruina Version

1.3.0

### Corail Tombstone Version

8.6.5

### What happened?

Server randomly crashed with "Ticking entity". Not entirely sure what triggered other than the ticking entity part and maybe because of a "Receptable" from Corail Tombstone.

### Gametype

Dedicated Server

### Occurence

Occurs rarely, not all the time.

### Other relevant mods

Modpack is TNP Limitless 7: https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-7

### Log Link

https://gist.githubusercontent.com/Gbergz/e886b799e2670299ff2b0826270bb2e6/raw/1b93c455a6b997ac446cf94b20e00e7fde29ba59/gistfile1.txt

```	at net.minecraft.world.level.storage.PlayerDataStorage.m_78435_(PlayerDataStorage.java:58) ~[server-1.20.1-20230612.114412-srg.jar%231383!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.irons_spellbooks.json:DataFixPlayerDataStorageMixin,pl:mixin:A}
	at ovh.corail.tombstone.helper.EntityHelper.loadPlayerData(EntityHelper.java:265) ~[tombstone-1.20.1-8.6.5.jar%231325!/:8.6.5] {re:mixin,re:classloading}
	at ovh.corail.tombstone.helper.EntityHelper.getOfflinePlayer(EntityHelper.java:273) ~[tombstone-1.20.1-8.6.5.jar%231325!/:8.6.5] {re:mixin,re:classloading}
	at ovh.corail.tombstone.item.ItemFamiliarReceptacle.captureSoul(ItemFamiliarReceptacle.java:221) ~[tombstone-1.20.1-8.6.5.jar%231325!/:8.6.5] {re:classloading}
	at ovh.corail.tombstone.event.EventHandler.onPreventDeath(EventHandler.java:411) ~[tombstone-1.20.1-8.6.5.jar%231325!/:8.6.5] {re:classloading}
	at ovh.corail.tombstone.event.__EventHandler_onPreventDeath_LivingDamageEvent.invoke(.dynamic) ~[tombstone-1.20.1-8.6.5.jar%231325!/:8.6.5] {re:classloading,pl:eventbus:B}
```

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Bawnorton** [comment]
This is not an issue with neruina. Neruina cannot handle client-ticking-exceptions (ticking exceptions thrown on the player's render thread) which is why the error is re-thrown. 2.0.0 which was just released handles them better but this is an issue with Corail's tombstones.

**Comment by Gbergz** [comment]
Gotcha, reported here due to dev of Tombstone noting the stacktraces of Neruina. Then closing the issue over there.

**Comment by Gbergz** [comment]
`https://github.com/Corail31/tombstone_lite/issues/221`
