### ISSUE TITLE
Mod doesn't work server-side

### ISSUE THREAD

**Issue by sternschnaube** [Benjamin-Norton/Neruina#66]
Received unknown remote registry entries from server
FabricRegistrySync
Render thread
Registry entry (neruina:errored) is missing from local registry (minecraft:data_component_type)
FabricRegistrySync
Registry entry (neruina:ticking_entry_id) is missing from local registry (minecraft:data_component_type)
net.fabricmc.fabric.impl.client.registry.sync.FabricRegistryClientInit
Registry remapping failed!
java.util.concurrent.CompletionException: net.fabricmc.fabric.impl.registry.sync.RemapException: Received 2 registry entries that are unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

neruina

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:145)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java)
	at net.minecraft.class_4093.wrapOperation$ddp000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting(class_4093.java:570)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.fabric.impl.registry.sync.RemapException: Received 2 registry entries that are unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

neruina

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:364)
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:260)
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:142)
	... 13 more

**Comment by venaminecraft** [comment]
Maybe this helps and is related to it: https://github.com/kikugie/elytra-trims/issues/56

**Comment by Bawnorton** [comment]
Annoying, I'll see if I can remove the syncing because these components don't need to be on the client.

**Comment by Bawnorton** [comment]
Fixed in 2.0.0-beta.5. Thanks for the reports.

**Comment by venaminecraft** [comment]
I have to thank you!
