### ISSUE TITLE
False Positive from voidcrafting recipies

### ISSUE THREAD

**Issue by NolanHewitt** [Benjamin-Norton/Neruina#76]
Recipes made using [voidcrafting](https://www.curseforge.com/minecraft/mc-mods/void-crafting) seem to falsely trigger this mods protection. For some reason this also results in the recipes providing double the output as well as logging in chat. Without this mod there doesn't seem to be any crashes or other issues while using voidcrafting from what I can tell.

**Comment by Bawnorton** [comment]
Got a log?

**Comment by NolanHewitt** [comment]
[latest.log](https://github.com/user-attachments/files/15543603/latest.log)
Here's the latest.log, had the neruina log occur a couple times before copying the log.

**Comment by NolanHewitt** [comment]
java.lang.IllegalArgumentException: data criterion 'voidcrafting:void_craft_success' does not exist
	at com.acikek.datacriteria.impl.DataCriteriaAPIImpl.getDataCriterion(DataCriteriaAPIImpl.java:19)
	at com.acikek.datacriteria.impl.DataCriteriaAPIImpl.trigger(DataCriteriaAPIImpl.java:23)
	at com.acikek.datacriteria.api.DataCriteriaAPI.trigger(DataCriteriaAPI.java:22)
	at com.acikek.voidcrafting.recipe.VoidRecipe.triggerCriterion(VoidRecipe.java:30)
	at com.acikek.voidcrafting.recipe.VoidRecipe.activate(VoidRecipe.java:37)
	at com.acikek.voidcrafting.VoidCrafting.lambda$registerEvent$0(VoidCrafting.java:43)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.acikek.voidcrafting.VoidCrafting.lambda$registerEvent$1(VoidCrafting.java:43)
	at com.acikek.voidcrafting.api.VoidCraftingAPI.lambda$static$0(VoidCraftingAPI.java:31)
	at net.minecraft.class_1297.handler$kcc000$voidcrafting$dropPreservedDust(class_1297.java:33832)
	at net.minecraft.class_1297.method_5825(class_1297.java)
	at net.minecraft.class_1297.method_31473(class_1297.java:553)
	at net.minecraft.class_1297.method_5670(class_1297.java:536)
	at net.minecraft.class_1297.method_5773(class_1297.java:474)
	at net.minecraft.class_1542.method_5773(class_1542.java:107)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.mixinextras$bridge$accept$201(class_1937.java)
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:91)
	at net.minecraft.class_1937.wrapOperation$icl000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:17048)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by NolanHewitt** [comment]
Got this from the "copy crash" option that generates in the chat log as well incase that helps

**Comment by Bawnorton** [comment]
Can't reproduce any crash, regardless Neruina stops error propagation so it can't "false positive" as it's literally hooking into the "mc is crashing process", in any case, Neruina is functioning as expected. Update void crafting and report this to them if it keeps happening.

**Comment by NolanHewitt** [comment]
It doesn’t crash with or without neruina, so I’m not sure why it pops up an error in chat. The only thing that really changes with this mod installed is that it doubles the item. I’ll report this to void crafting to see what they can do.
